spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/spectral
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
